### ISSUE TITLE
Add symfony autowiring config in wiki

### ISSUE THREAD

**Issue by cbastienbaron** [ankitpokhrel/tus-php#236]
**Is your feature request related to a problem? Please describe.**
For Symfony autowiring Wiki

**Describe the solution you'd like**
in services.yaml or other config file :

add 
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TusPhp\Cache\FileStore:
        class: TusPhp\Cache\FileStore
        arguments:
            $cacheDir: '%kernel.project_dir%/var/cache/'

    TusPhp\Tus\Server:
        class: TusPhp\Tus\Server
        arguments:
            $cacheAdapter: '@TusPhp\Cache\FileStore'
        calls:
            - method: setUploadDir
              arguments:
                - '%kernel.project_dir%/public/uploads'
            - method: setApiPath
              arguments:
                - '/files'
```

And boom TusPhp\Tus\Server can be injected configured via autowiring

**Describe alternatives you've considered**

**Additional context**

to save time for testing
