### ISSUE TITLE
Uppy -> tus-php (SF5)

### ISSUE THREAD

**Issue by Gompali** [ankitpokhrel/tus-php#251]
Hi, i tried to set up your symfony 5 example with auto-wiring and as your example
The server does not send any response header. I can have forgot something.

Here is my Vhost: 

```
<VirtualHost *:443>
 ServerName tus.example.tld
 DocumentRoot /var/www/tus.example.tld/public

 <Directory /var/www/tus.example.tld/public>
   AllowOverride All
   Order Allow,Deny
   Allow from All
   RewriteEngine on

   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteRule ^/(.*)?$ /index.php?$1 [QSA,L]
 </Directory>

 SSLEngine on
 SSLCertificateFile /etc/letsencrypt/live/tus.example.tld/fullchain.pem
 SSLCertificateKeyFile /etc/letsencrypt/live/tus.example.tld/privkey.pem
</VirtualHost>
```

The routes.yaml :

```
index:
    path: /tus
    controller: App\Controller\TusPhpController
 ```
services.yaml  :

```
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    TusPhp\Cache\FileStore:
        class: TusPhp\Cache\FileStore
        arguments:
            $cacheDir: '%kernel.project_dir%/var/cache/'

    TusPhp\Tus\Server:
        class: TusPhp\Tus\Server
        arguments:
            $cacheAdapter: '@TusPhp\Cache\FileStore'
        calls:
            - method: setUploadDir
              arguments:
                  - '%kernel.project_dir%/public/uploads'
            - method: setApiPath
              arguments:
                  - '/files'

```

Controller :

```
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use TusPhp\Tus\Server as TusServer;

class TusPhpController
{
    /**
     * @var TusServer
     */
    private $server;
    

    public function __construct(TusServer $server)
    {
        $this->server = $server;
    }

    public function __invoke(Request $request)
    {
        $response = $this->server->serve();

        return $response->send();
    }
}
```

The calling UI :

```
{% extends  'base.html.twig' %}

{% block stylesheets %}
    <link href="https://transloadit.edgly.net/releases/uppy/v1.10.1/uppy.min.css" rel="stylesheet">
{% endblock %}
{% block body %}

    <div id="drag-drop-area"></div>

    <script src="https://transloadit.edgly.net/releases/uppy/v1.10.1/uppy.min.js"></script>
    <script>
        var uppy = Uppy.Core()
            .use(Uppy.Dashboard, {
                trigger: '.UppyModalOpenerBtn',
                inline: true,
                replaceTargetContent: true,
                showProgressDetails: true,
                target: '#drag-drop-area'
            })
            .use(Uppy.Tus, {
                endpoint: 'https://tus.example.tld/tus',
                resume: true,
                autoRetry: true,
                retryDelays: [0, 1000, 3000, 5000]
            })

        uppy.on('complete', (result) => {
            console.log('Upload complete! We’ve uploaded these files:', result.successful)
        })
    </script>
{% endblock %}
```

I first have issues with CORS. Tried nelmio-cors-bundle, not working. 
The headers are not sent and not a single response is sent.
Then implemented a middleware : headers are sent in double and CORS is not working.
