### ISSUE TITLE
[Symfony] CORS headers not present

### ISSUE THREAD

**Issue by ThibaultVlacich** [ankitpokhrel/tus-php#296]
I'm trying to integrate tus-php into my Symfony project.

My issue is that XHR requests are blocked by my browser because CORS header allow-origin is not present.

Here's my very simple Symfony controller:

```php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use TusPhp\Tus\Server;

class FilesController extends AbstractController
{
    /**
     * Create tus server.
     *
     * @Route("/files/", name="tus_post")
     * @Route("/files/{token?}", name="tus", requirements={"token"=".+"})
     *
     * @param TusService $tusService
     *
     * @return Response
     */
    public function server(Server $server)
    {
        $response = $server->serve();

        return $response->send();
    }
}
```

I tried many things. I have the Nelmio Cors Bundle installed into my project to handle cors.
So I tried: skipping the default "Cors" middleware of tus-php and adding this to the nelmio_cors.yml config:

```yaml
nelmio_cors:
    paths:
        '^/files/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'POST', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS']
            allow_headers: ['Authorization', 'Origin', 'X-Requested-With', 'Content-Type', 'Content-Length', 'Upload-Key', 'Upload-Checksum', 'Upload-Length', 'Upload-Offset', 'Tus-Version', 'Tus-Resumable', 'Upload-Metadata']
            expose_headers: ['Upload-Key', 'Upload-Checksum', 'Upload-Length', 'Upload-Offset', 'Upload-Metadata', 'Tus-Version', 'Tus-Resumable', 'Tus-Extension', 'Location']
            max_age: 86400
```

NB: the env var `CORS_ALLOW_ORIGIN` is properly set and works on other endpoints handled directly by Symfony.

I also tried this config to bypass the Nelmio Cors Bundle, and leaving the default Cors middleware do it's job:
```yaml
nelmio_cors:
    paths:
        '^/files/': null
```

None of this is working. Any idea on how what I could be missing?

EDIT: Btw, I am using Uppy for the client.
